//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoDAL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int NoteId { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
        public int GroupId { get; set; }
        public bool StatusId { get; set; }
        public string UserId { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
